package com.example.grace.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.supplier_name
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private String supplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id_card
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.category_name
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.quantity
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private BigDecimal quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.unit_price
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_price
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.units_measure
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private String unitsMeasure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.formula_mode
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private String formulaMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.have_certificate
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private String haveCertificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.remark
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.created_time
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.last_updated_time
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private Date lastUpdatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.del_flag
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.supplier_name
     *
     * @return the value of order.supplier_name
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.supplier_name
     *
     * @param supplierName the value for order.supplier_name
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id_card
     *
     * @return the value of order.id_card
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id_card
     *
     * @param idCard the value for order.id_card
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.category_name
     *
     * @return the value of order.category_name
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.category_name
     *
     * @param categoryName the value for order.category_name
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.quantity
     *
     * @return the value of order.quantity
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.quantity
     *
     * @param quantity the value for order.quantity
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.unit_price
     *
     * @return the value of order.unit_price
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.unit_price
     *
     * @param unitPrice the value for order.unit_price
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_price
     *
     * @return the value of order.total_price
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_price
     *
     * @param totalPrice the value for order.total_price
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.units_measure
     *
     * @return the value of order.units_measure
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public String getUnitsMeasure() {
        return unitsMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.units_measure
     *
     * @param unitsMeasure the value for order.units_measure
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setUnitsMeasure(String unitsMeasure) {
        this.unitsMeasure = unitsMeasure == null ? null : unitsMeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.formula_mode
     *
     * @return the value of order.formula_mode
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public String getFormulaMode() {
        return formulaMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.formula_mode
     *
     * @param formulaMode the value for order.formula_mode
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setFormulaMode(String formulaMode) {
        this.formulaMode = formulaMode == null ? null : formulaMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.have_certificate
     *
     * @return the value of order.have_certificate
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public String getHaveCertificate() {
        return haveCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.have_certificate
     *
     * @param haveCertificate the value for order.have_certificate
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setHaveCertificate(String haveCertificate) {
        this.haveCertificate = haveCertificate == null ? null : haveCertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.remark
     *
     * @return the value of order.remark
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.remark
     *
     * @param remark the value for order.remark
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.created_time
     *
     * @return the value of order.created_time
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.created_time
     *
     * @param createdTime the value for order.created_time
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.last_updated_time
     *
     * @return the value of order.last_updated_time
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.last_updated_time
     *
     * @param lastUpdatedTime the value for order.last_updated_time
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.del_flag
     *
     * @return the value of order.del_flag
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.del_flag
     *
     * @param delFlag the value for order.del_flag
     *
     * @mbg.generated Mon Mar 13 10:22:52 CST 2023
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}